<?php

namespace Database\Seeders;

use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $users = [
            [
                // 'codigo_id'        =>  1,
                'nombres'          =>  'Dennis',
                'apellidos'        =>  'PWG',
                'numero_documento' =>  '1234567891111',
                'telefono'         =>  '63443212',
                'email'            =>  'dev@paginawebguatemala.com',
                'direccion'        =>  'Ciudad de Guatemala',
                'pais_id'          =>  1,
                'user_type_id'     =>  1,

                'company_id'       =>  1,
                'branch'           =>  'Sucursal 12',
                'colegiado'        => null,
                'region'           => null,
                'visitor_id'       => null,

                'accepted_terms_version' => '1.0.0',
                'password'         =>  Hash::make(env('DEFAULT_PASS')),
                'created_at'       =>  (Carbon::now())->toDateTimeString(),
            ],

            [
                // 'codigo_id'        =>  2,
                'nombres'          =>  'Dwight',
                'apellidos'        =>  'PWG',
                'numero_documento' =>  '1234567891112',
                'telefono'         =>  '63443212',
                'email'            =>  'app@paginawebguatemala.com',
                'direccion'        =>  'Ciudad de Guatemala',
                'pais_id'          =>  1,
                'user_type_id'     =>  1,

                'company_id'       =>  2,
                'branch'           =>  'Sucursal 20',
                'colegiado'        => null,
                'region'           => null,
                'visitor_id'       => null,

                'accepted_terms_version' => '1.0.0',
                'password'         =>  Hash::make(env('DEFAULT_PASS')),
                'created_at'       =>  (Carbon::now())->toDateTimeString(),
            ],

            [
                // 'codigo_id'        =>  13,
                'nombres'          =>  'Revisor',
                'apellidos'        =>  'Google',
                'numero_documento' =>  '1234567891113',
                'telefono'         =>  '39987867',
                'email'            =>  'revisor@email.com',
                'direccion'        =>  'Ciudad de Guatemala',
                'pais_id'          =>  1,
                'user_type_id'     =>  2,

                'company_id'       =>  null,
                'branch'           =>  null,
                'colegiado'        => '43552',
                'region'           => null,
                'visitor_id'       => 1,

                'accepted_terms_version' => '1.0.0',
                'password'         =>  Hash::make(env('DEFAULT_PASS')),
                'created_at'       =>  (Carbon::now())->toDateTimeString(),
            ],

            [
                // 'codigo_id'        =>  14,
                'nombres'          =>  'Revisor',
                'apellidos'        =>  'IOS',
                'numero_documento' =>  '1234567891114',
                'telefono'         =>  '83323462',
                'email'            =>  'revisorios@email.com    ',
                'direccion'        =>  'Ciudad de Guatemala',
                'pais_id'          =>  1,
                'user_type_id'     =>  2,

                'company_id'       =>  null,
                'branch'           =>  null,    
                'colegiado'        => '43552',
                'region'           => 'Central',
                'visitor_id'       => 2,

                'accepted_terms_version' => '1.0.0',
                'password'         =>  Hash::make(env('DEFAULT_PASS')),
                'created_at'       =>  (Carbon::now())->toDateTimeString(),
            ],
        ];

        DB::table('users')->insert($users);

        User::whereIn('id', [1, 2])->each(fn (User $user) => $user->assignRole('admin'));
        User::whereIn('id', [3, 4])->each(fn (User $user) => $user->assignRole('participant'));

        // 500 dependientes (tipo 1) — mixto GT y HN
        // User::factory()->count(250)->dependiente(paisId: 1)->create();
        // User::factory()->count(250)->dependiente(paisId: 2)->create();

        // 500 doctores (tipo 2) — mixto GT y HN
        // User::factory()->count(250)->doctor(paisId: 1)->create();
        // User::factory()->count(250)->doctor(paisId: 2)->create();

        // Usuarios para laboratorio
        $lab_users = [
            [
                'nombres' => 'ADA SHEKENIA',
                'apellidos' => 'BARILLAS CASTILLO',
                'puesto' => 'ANALISTA DE VALIDACIONES',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ALICIA',
                'apellidos' => 'PEDRO DIEGO',
                'puesto' => 'ANALISTA DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ALMARY GABRIELA',
                'apellidos' => 'CHAMALÉ LINARES',
                'puesto' => 'ESPECIALISTA EN LOGÍSTICA DE LABORATORIO ANALÍTICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ANA BEATRIZ',
                'apellidos' => 'RUANO GARCIA',
                'puesto' => 'JEFE DE LABORATORIO DE MICROBIOLOGIA',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ANGEL ORLANDO',
                'apellidos' => 'ORTIZ CATALAN',
                'puesto' => 'ESPECIALISTA EN CALIFICACIÓN DE EQUIPOS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ANGIE GABRIELA',
                'apellidos' => 'HERNÁNDEZ MAZARIEGOS',
                'puesto' => 'INSPECTOR DE PROCESO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'AXEL RAMIRO',
                'apellidos' => 'IXCAJOC GODÍNEZ',
                'puesto' => 'ANALISTA FISICOQUIMICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'BLANCA MARISOL',
                'apellidos' => 'CALDERON MAZARIEGOS',
                'puesto' => 'ASISTENTE DE GER. GAR. CAL.',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'BRENDA YAJAIRA',
                'apellidos' => 'QUEZADA MONTERROSO',
                'puesto' => 'AUXILIAR DE LABORATORIO FISICOQUIMICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'BYRON',
                'apellidos' => 'GUEVARA LUTIN',
                'puesto' => 'AUXILIAR DE VAL. MÉTODOS MICROBIOLÓGICOS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'CARMEN JUSTINA',
                'apellidos' => 'ALEJANDRA BALDETTI',
                'puesto' => 'JEFE DE DOCUMENTACION Y CALIFICACIONES',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'CLAUDIA MARIA',
                'apellidos' => 'SIGUI BRAN DE ENRIQUEZ',
                'puesto' => 'GERENTE DE GARANTIA DE CALIDAD Y DT',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'CRISTIAN ESAU',
                'apellidos' => 'CALITO MIRANDA',
                'puesto' => 'INSPECTOR DE PROCESO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'CRISTIAN NEHEMIAS',
                'apellidos' => 'DOMINGO VELASQUEZ',
                'puesto' => 'INSPECTOR DE PROCESO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'DANIELA ALEJANDRA',
                'apellidos' => 'VEGA CHANG',
                'puesto' => 'ESPECIALISTA EN ASUNTOS REGULATORIOS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'DAYRI NOEMÍ',
                'apellidos' => 'REQUENA GÓMEZ',
                'puesto' => 'ESPECIALISTA EN DOCUMENTACIÓN A.C.',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'DENIS IVÁN',
                'apellidos' => 'GÓMEZ GONZÁLEZ',
                'puesto' => 'INSPECTOR DE PROCESO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'EDGAR MARIO',
                'apellidos' => 'RECINOS MARTÍNEZ',
                'puesto' => 'ESPECIALISTA EN CALIFICACIÓN DE EQUIPOS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'EDWIN DAVID',
                'apellidos' => 'POP CHOC',
                'puesto' => 'INSPECTOR DE PROCESO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ERICK IVAN',
                'apellidos' => 'IXCOT AJPOP',
                'puesto' => 'ESP. EN VALIDACION DE SISTEMAS CRITICOS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'GERSON ELIEZER ANTONIO',
                'apellidos' => 'MENCOS BARRERA',
                'puesto' => 'ANALISTA DE MATERIAS PRIMAS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'GERSON ROBERTO',
                'apellidos' => 'PINEDA GONZÁLEZ',
                'puesto' => 'ANALISTA FISICOQUÍMICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'GLADYS STEFANY',
                'apellidos' => 'CASTRO GARCÍA',
                'puesto' => 'INSPECTOR DE PROCESO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'HECTOR HUGO',
                'apellidos' => 'ESQUIVEL VENTURA',
                'puesto' => 'ANALISTA FISICOQUIMICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'HELEN MARIELA',
                'apellidos' => 'VELASQUEZ MONTERROSO',
                'puesto' => 'ESPECIALISTA EN DOCUMENTACIÓN',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'HUMBERTO FABIO GABRIEL',
                'apellidos' => 'JACOBO GONZÁLEZ',
                'puesto' => 'ESPECIALISTA EN RESOLUCIONES',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'INGRID AZUCENA',
                'apellidos' => 'ZUÑIGA OSOY',
                'puesto' => 'INSPECTOR DE PROCESO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JEIMY NINETH',
                'apellidos' => 'RAMIREZ PACAY',
                'puesto' => 'INSPECTOR DE PROCESO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JENNER GIOVANY',
                'apellidos' => 'JUAREZ LACANAL',
                'puesto' => 'SUPERVISOR TÉCNICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JONATHAN GABRIEL',
                'apellidos' => 'ARANGO BOCH',
                'puesto' => 'INSPECTOR DE PROCESO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JORGE ESTUARDO',
                'apellidos' => 'CARDONA ORANTES',
                'puesto' => 'ANALISTA FISICOQUIMICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JORGE',
                'apellidos' => 'ESTUARDO DE LA ROCA GIRALT',
                'puesto' => 'ESPECIALISTA EN DOCUMENTACIÓN DE LABORATORIO FQ',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JOSÉ EDUARDO',
                'apellidos' => 'BOCHE CASTRO',
                'puesto' => 'INSPECTOR DE PROCESO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JOSE MANUEL',
                'apellidos' => 'TORRES JIMENEZ',
                'puesto' => 'INSPECTOR DE PROCESO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'KARIN EUNICE',
                'apellidos' => 'ESTRADA MORALES',
                'puesto' => 'ESPECIALISTA EN ASUNTOS REGULATORIOS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'KARLA AZUCENA',
                'apellidos' => 'ESTRADA DONIS',
                'puesto' => 'ESPECIALISTA TÉCNICO NORMATIVO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'KEVIN ABIEL',
                'apellidos' => 'GUTIÉRREZ SIL',
                'puesto' => 'ESPECIALISTA EN CALIFICACIÓN DE ÁREAS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'KEVIN EMILIO',
                'apellidos' => 'AGUILAR HERNÁNDEZ',
                'puesto' => 'ESPECIALISTA EN VALIDACIÓN DE PROCESOS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'LESTER WALDEMAR',
                'apellidos' => 'VALIENTE IXLAJ',
                'puesto' => 'INSPECTOR DE PROCESO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'LIGIA MARIA CRISTINA',
                'apellidos' => 'HERNANDEZ CHAVEZ',
                'puesto' => 'ESP. DE VALID.METODO MICROBIOLOGICOS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'MARIA CRISTINA',
                'apellidos' => 'AVENDAÑO QUINTANA',
                'puesto' => 'ESPECIALISTA EN VALIDACIÓN DE PROCESOS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'MARCELA PAVLOVA',
                'apellidos' => 'CASTELLANOS PÉREZ',
                'puesto' => 'ANALISTA DE VALIDACIONES',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'MARLON ROLANDO',
                'apellidos' => 'VILLATORO VEGA',
                'puesto' => 'JEFE DE LABORATORIO ANALÍTICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'MIGUEL FRANCISCO',
                'apellidos' => 'AROCHE CARBALLO',
                'puesto' => 'JEFE DE INSPECCION',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'NANDY LORENA',
                'apellidos' => 'NUFIO MARTINEZ',
                'puesto' => 'JEFE DE VALIDACIONES',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'OLIVER ALEXANDER',
                'apellidos' => 'RIVERA GARCÍA',
                'puesto' => 'ANALISTA DE VALIDACIONES',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'OSVIN ESTUARDO',
                'apellidos' => 'ROJOP REYES',
                'puesto' => 'ANALISTA FISICOQUÍMICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'RODRIGO ANTONIO',
                'apellidos' => 'DÍAZ ARIAS',
                'puesto' => 'ESPECIALISTA EN VALIDACIÓN DE SISTEMAS CRITICOS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ROSA HERMINDA',
                'apellidos' => 'LOPEZ MORALES',
                'puesto' => 'AUXILIAR DE MICROBIOLOGIA',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'SARA BEATRIZ',
                'apellidos' => 'CUTZAL MORALES',
                'puesto' => 'JEFE DE ASUNTOS REGULATORIOS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'SERGIO ALBERTO',
                'apellidos' => 'MENENDEZ MORALES',
                'puesto' => 'ESPECIALISTA EN VALIDACION DE PROCESOS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'SERGIO ESTUARDO',
                'apellidos' => 'RODRÍGUEZ URIZAR',
                'puesto' => 'ANALISTA DE VALIDACIONES',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'SILVIA MAYARI CERVANTES',
                'apellidos' => 'MARTINEZ DE',
                'puesto' => 'JEFE DE ASEGURAMIENTO DE CALIDAD',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'STEFANIE JOHANNA',
                'apellidos' => 'HERNÁNDEZ SAGASTUME',
                'puesto' => 'ANALISTA FISICOQUÍMICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'TIFANY MARISOL',
                'apellidos' => 'REYES ARÉVALO',
                'puesto' => 'ESPECIALISTA EN VALIDACIÓN DE MÉTODOS ANALÍTICOS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'VALERIA',
                'apellidos' => 'MAYEN REYNA',
                'puesto' => 'ANALISTA DE MICROBIOLOGÍA',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'WENDY MISHEL',
                'apellidos' => 'CHAY LÓPEZ',
                'puesto' => 'ESPECIALISTA EN VALIDACIÓN DE SISTEMAS INFORMÁTICOS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'WILLIAM ALEXANDER',
                'apellidos' => 'ALVARADO JUÁREZ',
                'puesto' => 'ANALISTA DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'WILSON DAVID',
                'apellidos' => 'CONTRERAS CARRERA',
                'puesto' => 'INSPECTOR DE PROCESO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'YASLIN LEONEL',
                'apellidos' => 'HERNANDEZ OSOY',
                'puesto' => 'ANALISTA DE AGUAS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'YURI YOVANI',
                'apellidos' => 'MARTÍNEZ SANTOS',
                'puesto' => 'AUXLIAR DE VALIDACIÓN DE MÉTODOS MICROBIOLÓGICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'MARIA JOSÉ',
                'apellidos' => 'ALVARADO CASTELLANOS',
                'puesto' => 'VISITADOR MEDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JUAN CARLOS',
                'apellidos' => 'GÁLVEZ CARDONA',
                'puesto' => 'VISITADOR MEDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'CRUZ FERNANDO',
                'apellidos' => 'ARANA URRUTIA',
                'puesto' => 'GERENTE DE DISTRITO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'LUIS',
                'apellidos' => 'MANUEL MALDONADO DE LEÓN',
                'puesto' => 'VISITADOR MEDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'FREDY ROLANDO',
                'apellidos' => 'CÁMBARA PAIZ',
                'puesto' => 'GERENTE DE DISTRITO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'PABLO ALEJANDRO',
                'apellidos' => 'BARRIOS TOLOSA',
                'puesto' => 'VISITADOR MEDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JOSÉ WILSTON',
                'apellidos' => 'FIGUEROA AGUILAR',
                'puesto' => 'GERENTE DE DISTRITO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ELDER ALFONSO',
                'apellidos' => 'DÍAZ PELÁEZ',
                'puesto' => 'GERENTE DE DISTRITO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'MARIA ALEJANDRA VELÁSQUEZ',
                'apellidos' => 'PAREDES ESPAÑA',
                'puesto' => 'VISITADOR MEDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'BYRON SALVADOR',
                'apellidos' => 'ESTRADA ORTIZ',
                'puesto' => 'VISITADOR MEDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'DULCE',
                'apellidos' => 'MARÍA RAMOS',
                'puesto' => 'VISITADOR MEDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'GENZER ENGADI',
                'apellidos' => 'GONZÁLEZ LÓPEZ',
                'puesto' => 'VISITADOR MEDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'FRANCISCO JOSÉ',
                'apellidos' => 'GIRÓN DÍAZ',
                'puesto' => 'VISITADOR MEDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'IRIS MARISOL',
                'apellidos' => 'TRUJILLO MENA',
                'puesto' => 'VISITADOR MEDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'DENNIS FRANCISCO',
                'apellidos' => 'VALDERRAMOS MORALES',
                'puesto' => 'VISITADOR MEDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'LESTER EDUARDO',
                'apellidos' => 'ILLESCAS URLA',
                'puesto' => 'VISITADOR MEDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'IVAN ARMANDO',
                'apellidos' => 'AZURDIA ALVIZURES',
                'puesto' => 'VISITADOR MEDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'KARLA LETICIA',
                'apellidos' => 'JUÁREZ ROSALES',
                'puesto' => 'VISITADOR MEDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'MARTHA MARIA MAGDALENA',
                'apellidos' => 'ESPINOZA RIVERA',
                'puesto' => 'GERENTE DE DISTRITO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ONAYDA',
                'apellidos' => 'JUDIZA DE LEON MAZARIEGOS',
                'puesto' => 'VISITADOR MEDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'GERBER ANTONIO',
                'apellidos' => 'SOLARES CALVILLO',
                'puesto' => 'VISITADOR MEDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JUAN FERNANDO',
                'apellidos' => 'JURACÁN ARGUETA',
                'puesto' => 'ANALISTA DE MERCADOS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'CANDY LUCREZIA',
                'apellidos' => 'FIGUEROS MEZA',
                'puesto' => 'AUXILIAR DE VENTAS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'CÉSAR',
                'apellidos' => 'ANÍBAL DE PAZ CHAPERNO',
                'puesto' => 'EJECUTIVO DE CUENTAS PRINCIPALES',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'IRMA LETICIA',
                'apellidos' => 'QUIÑÓNEZ GÓMEZ',
                'puesto' => 'ASISTENTE GERENCIA DE PROMOCION MEDICA',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'EDWIN OBDULIO',
                'apellidos' => 'HERRERA CORTEZ',
                'puesto' => 'VISITADOR MEDICO JUNIOR',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'HANS WILLIAMS',
                'apellidos' => 'MONROY MORALES',
                'puesto' => 'GERENTE DE PROMOCION MEDICA',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'MARIO',
                'apellidos' => 'FERNANDO DE LEÓN GONZÁLEZ',
                'puesto' => 'VISITADOR MEDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JOSÉ RICARDO',
                'apellidos' => 'CHAJÓN CASTILLO',
                'puesto' => 'VISITADOR MEDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JINMY ESTUARDO',
                'apellidos' => 'MONTERROSO MALDONADO',
                'puesto' => 'VISITADOR MEDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'RICARDO FRANCISCO',
                'apellidos' => 'GATICA OQUENDO',
                'puesto' => 'VISITADOR MEDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JULIO ALBERTO',
                'apellidos' => 'RODRÍGUEZ MORATAYA',
                'puesto' => 'VISITADOR MEDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JOSELIN MARIELOS',
                'apellidos' => 'TELÓN ORELLANA',
                'puesto' => 'VISITADOR MEDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'GREYSSI MARIELA',
                'apellidos' => 'MAZÁ TRUJILLO',
                'puesto' => 'VISITADOR MEDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JORGE MARIO',
                'apellidos' => 'LÓPEZ GONZÁLEZ',
                'puesto' => 'VISITADOR MEDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'CARLOS VÍCTOR IVÁN',
                'apellidos' => 'VELÁSQUEZ IXCOP',
                'puesto' => 'VISITADOR MEDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'MARILIN PAOLA',
                'apellidos' => 'MEJÍA COSAJAY',
                'puesto' => 'VISITADOR MEDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'KAREN IVETTE',
                'apellidos' => 'LIMA QUELEX',
                'puesto' => 'VISITADOR MEDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'MARIO ALFREDO',
                'apellidos' => 'FUENTES CASTILLO',
                'puesto' => 'VISITADOR MEDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ENRIQUE JOSÉ',
                'apellidos' => 'MORATAYA PACHECO',
                'puesto' => 'VISITADOR MÉDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'LESLY JEANETHE',
                'apellidos' => 'KUCKLING SOLÍS',
                'puesto' => 'VISITADOR MÉDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JOSÉ GEOVANY',
                'apellidos' => 'TENAS MATEO',
                'puesto' => 'VISITADOR MEDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'MERSY ABIGAIL',
                'apellidos' => 'MORALES SOTO',
                'puesto' => 'VISITADOR MEDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'OMAR ALFREDO',
                'apellidos' => 'ERICASTILLA SAMAYOA',
                'puesto' => 'GERENTE LÍNEA ÉTICA',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'KAREN ALEJANDRA',
                'apellidos' => 'GUZMÁN ROSALES',
                'puesto' => 'JEFE DE DISEÑO GRÁFICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'CELA PATRICIA',
                'apellidos' => 'LOZA PÁEZ',
                'puesto' => 'GERENTE DE PRODUCTO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ALEJANDRA NINETH',
                'apellidos' => 'JUAREZ LEÓN',
                'puesto' => 'ASISTENTE DE MERCADEO ETICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'AXEL DAVID',
                'apellidos' => 'ZAMORA GARCÍA',
                'puesto' => 'ANALISTA DE INVESTIGACION DE MERCADOS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'KAREN XIOMARA',
                'apellidos' => 'ROMÁN AGUILAR',
                'puesto' => 'ANALISTA DE VISITA MÉDICA Y COMERCIAL',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ANDREA LUCÍA',
                'apellidos' => 'MORALES MATA',
                'puesto' => 'GERENTE DE LÍNEA OTC - OTX',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'EMMA JANETH',
                'apellidos' => 'CHAN MIRÓN',
                'puesto' => 'JEFE TELEVENTAS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'HEYDY ESTELA',
                'apellidos' => 'QUEVEDO GARCÍA',
                'puesto' => 'AUXILIAR TELEVENTAS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ADILIA ILIANA',
                'apellidos' => 'ESTRADA CHAPETÓN',
                'puesto' => 'EJECUTIVO DE CUENTAS PRINCIPALES',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'LUIS FERNANDO',
                'apellidos' => 'GALINDO GUTIÉRREZ',
                'puesto' => 'VENDEDOR COMERCIAL',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ELÍAS',
                'apellidos' => 'MÉNDEZ HOIL',
                'puesto' => 'VENDEDOR COMERCIAL',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'OSCAR ARNOLDO',
                'apellidos' => 'MORATAYA HERNÁNDEZ',
                'puesto' => 'VENDEDOR COMERCIAL',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JOSÉ LUIS',
                'apellidos' => 'GÓMEZ ELÍAS',
                'puesto' => 'VENDEDOR COMERCIAL',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'OSCAR ROMEO',
                'apellidos' => 'ESCRIBÁ MONROY',
                'puesto' => 'VENDEDOR COMERCIAL',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'MARCO VINICIO',
                'apellidos' => 'TEJADA MELGAR',
                'puesto' => 'VENDEDOR COMERCIAL',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ALLAN JOSUÉ',
                'apellidos' => 'AGUILAR MARROQUÍN',
                'puesto' => 'VENDEDOR COMERCIAL',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'KRISTHIAN ANTONIO',
                'apellidos' => 'BARAHONA VÁSQUEZ',
                'puesto' => 'ASESOR MEDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'RODRIGO',
                'apellidos' => 'ARGUEDAS',
                'puesto' => 'ASESOR MEDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'MARÍA SONIA',
                'apellidos' => 'CASTILLO ALVARADO',
                'puesto' => 'VISITADOR MEDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'SHARON ISABEL',
                'apellidos' => 'POZUELOS PINEDA',
                'puesto' => 'VISITADOR MEDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'PABLO JOSÉ',
                'apellidos' => 'LEMUS ROMÁN',
                'puesto' => 'VISITADOR MEDICO INSTITUCIONAL',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ALLAN',
                'apellidos' => 'RENÉ ARREAGA DE LEÓN',
                'puesto' => 'VISITADOR MEDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'AMANDA BERENISSE',
                'apellidos' => 'MORENO FLORES',
                'puesto' => 'ASISTENTE DE MERCADEO OTC - OTX',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'CHRISTIAN JOSUÉ',
                'apellidos' => 'DÍAZ PANTZAY',
                'puesto' => 'DISEÑADOR GRAFICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'FERNANDO ALFONSO',
                'apellidos' => 'RUIZ ESQUIVEL',
                'puesto' => 'VISITADOR MÉDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'CELESTE ANAYANSEE',
                'apellidos' => 'TELLO MENDOZA',
                'puesto' => 'GERENTE DE PRODUCTO ÉTICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ANDREA CECILIA',
                'apellidos' => 'DONIS MARTÍNEZ DE GARCÍA',
                'puesto' => 'GERENTE DE PRODUCTOS ÉTICOS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ELMER OSWALDO',
                'apellidos' => 'ALONZO BRIONES',
                'puesto' => 'VISITADOR MEDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'WERNER ESTUARDO',
                'apellidos' => 'DÍAZ GIRÓN',
                'puesto' => 'VISITADOR MEDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'EVERTH LEONEL',
                'apellidos' => 'MARROQUÍN ESTRADA',
                'puesto' => 'VISITADOR MEDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'YENNI LISET',
                'apellidos' => 'MIRANDA MUÑOZ',
                'puesto' => 'VISITADOR MEDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'VERA LUCÍA',
                'apellidos' => 'VILLALTA MUÑOZ',
                'puesto' => 'IMPULSADORA',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JOSUÉ DANIEL',
                'apellidos' => 'TALA GONZÁLEZ',
                'puesto' => 'VISITADOR MÉDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JORGE ANTONIO',
                'apellidos' => 'MUÑOZ ECHEVERRÍA',
                'puesto' => 'VISITADOR MÉDICO - RUNNER',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ADAMARIS SAMANTHA',
                'apellidos' => 'GODOY RAMOS',
                'puesto' => 'VISITADOR MÉDICO - RUNNER',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'AMANDA MISHEL',
                'apellidos' => 'GONZÁLEZ MARROQUÍN',
                'puesto' => 'VISITADOR MÉDICO - GINECO URO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'LIGDA ABIGAIL',
                'apellidos' => 'PEREZ NAVAS',
                'puesto' => 'VISITADOR MEDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'MARÍA ANGELA',
                'apellidos' => 'MENCOS ORANTES',
                'puesto' => 'VISITADOR MEDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JOSE ALFREDO',
                'apellidos' => 'DÍAZ MORÁN',
                'puesto' => 'VISITADOR MEDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'MARÍA FERNANDA',
                'apellidos' => 'VALDEZ RAVANALES',
                'puesto' => 'VISITADOR MEDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'LUIS DIEGO',
                'apellidos' => 'CARRASCOSA GUTIÉRREZ',
                'puesto' => 'VISITADOR MÉDICO RUNNER QUETZALTENANGO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'MADELIN YESENIA',
                'apellidos' => 'MIJANGOS FLORES',
                'puesto' => 'VISITADOR MÉDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'SERGIO ANTONIO',
                'apellidos' => 'FERNÁNDEZ VÁSQUEZ',
                'puesto' => 'VISITADOR MÉDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ALLAN RICARDO',
                'apellidos' => 'ALONZO COTZAJAY',
                'puesto' => 'ADMINISTRADOR DE PLATAFORMA DE FIDELIZACION DONOLIFE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'SANDRA LISSETH',
                'apellidos' => 'GAMARRO SANTOS',
                'puesto' => 'IMPULSADORA',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ÉLDIDA FLORINDA',
                'apellidos' => 'ESCALANTE ROBLERO',
                'puesto' => 'IMPULSADORA HUEHUETENANGO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JOSEPH ANTHONY',
                'apellidos' => 'ILLESCAS GUEVARA',
                'puesto' => 'VISITADOR MÉDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'BRENDA REGINA',
                'apellidos' => 'LÓPEZ MÁRQUEZ',
                'puesto' => 'VISITADOR MÉDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'HUMBERTO JOSUÉ',
                'apellidos' => 'CALDERÓN ALVARADO',
                'puesto' => 'VISITADOR MÉDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'MARIO JOSÉ',
                'apellidos' => 'ORTIZ RUÍZ',
                'puesto' => 'VISITADOR MÉDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ANNY JEOMARA',
                'apellidos' => 'MONROY ÁLVAREZ',
                'puesto' => 'PROMOTOR',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'NIDIA ESTELA',
                'apellidos' => 'ORTIZ SIAN',
                'puesto' => 'PROMOTOR',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'KARINA ABIGAIL',
                'apellidos' => 'MEDINA VELASQUEZ',
                'puesto' => 'PROMOTOR',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JAVIER ALEJANDRO',
                'apellidos' => 'LEAL JIMÉNEZ',
                'puesto' => 'PROMOTOR',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ELISABET MICHEL',
                'apellidos' => 'IXCOLIN PEREIRA',
                'puesto' => 'IMPULSADORA',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'RUBIDIA',
                'apellidos' => 'ESMERALDA ZAPETA DE VILLALBA',
                'puesto' => 'IMPULSADORA',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'DARLIN BETHZAVEL',
                'apellidos' => 'CARDONA REYES',
                'puesto' => 'IMPULSADORA',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JORGE ALEJANDRO',
                'apellidos' => 'SOLARES ARRIOLA',
                'puesto' => 'VISITADOR MÉDICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'KATHERINE ANDREA',
                'apellidos' => 'MURALLES CONTRERAS',
                'puesto' => 'PROMOTOR',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'EMILY MICHELLE',
                'apellidos' => 'VASQUEZ GONZÁLEZ',
                'puesto' => 'COMMUNITY MANAGER  Y DISEÑADOR GRAFICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'EVELIN RAQUEL',
                'apellidos' => 'RUANO ENRÍQUEZ',
                'puesto' => 'GERENTE DE PRODUCTO OTC-OTX',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'LIZA MARÍA',
                'apellidos' => 'MARTÍNEZ CHANG',
                'puesto' => 'GERENTE DE PRODUCTO JUNIOR OTC OTX',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JESSIKA EUGENIA',
                'apellidos' => 'HERNANDEZ ESTRADA DE HILARIO',
                'puesto' => 'KAM INSTITUCIONAL',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ADOLFO GIOVANI',
                'apellidos' => 'AYALA BÚCARO',
                'puesto' => 'GERENTE DE DESARROLLO DE NUEVOS NEGOCIOS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'EDDY DAVID',
                'apellidos' => 'CALDERÓN AGUILAR',
                'puesto' => 'JEFE DE COSTOS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ANA DEL ROSARIO',
                'apellidos' => 'SILOÉ GONZÁLEZ',
                'puesto' => 'JEFE DE CREDITOS Y COBROS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'LUIS FERNANDO',
                'apellidos' => 'MURALLES PIRIR',
                'puesto' => 'ENCARGADO DE BODEGA MUESTRA MEDICA',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'GUILLERMO ALFREDO',
                'apellidos' => 'RIVERA MEJÍA',
                'puesto' => 'ASISTENTE DE COMPRAS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'BYRON RENÉ',
                'apellidos' => 'ÁLVAREZ BARRIENTOS',
                'puesto' => 'ASISTENTE DE CONTABILIDAD',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JONATAN ABISAI',
                'apellidos' => 'ALVAREZ SICAY',
                'puesto' => 'ASISTENTE DE TESORERÍA',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'GLENDA ANIDALIA',
                'apellidos' => 'GÓMEZ TOCAY',
                'puesto' => 'CONSERJE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ERWIN',
                'apellidos' => 'BOCHE MACHÍN',
                'puesto' => 'MENSAJERO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JOSE GERARDO',
                'apellidos' => 'GUAMUCH BOROR',
                'puesto' => 'MENSAJERO COBRADOR',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'BYRON ALEXANDER',
                'apellidos' => 'CARACÚN ARIAS',
                'puesto' => 'ASISTENTE DE CREDITOS Y COBROS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'EDGAR YOVANI',
                'apellidos' => 'PICHOL UZ',
                'puesto' => 'ASISTENTE DE COBROS Y CRÉDITOS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'DARWIN DANIEL',
                'apellidos' => 'MÉNDEZ PATZÁN',
                'puesto' => 'ASISTENTE DE COBROS Y CRÉDITOS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'EDDY ARIEL',
                'apellidos' => 'SOTO ESPINOZA',
                'puesto' => 'AUXILIAR DE BODEGA',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'OLMAN LISANDRO',
                'apellidos' => 'CRUZ MO',
                'puesto' => 'AUXILIAR DE BODEGA',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'SERGIO TOMÁS',
                'apellidos' => 'MENDOZA MENDOZA',
                'puesto' => 'AUXILIAR DE BODEGA',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'LESTER FABRICIO',
                'apellidos' => 'DÁVILA SECAIDA',
                'puesto' => 'ASISTENTE FINANCIERO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'LUIS ARTURO',
                'apellidos' => 'PÉREZ MENDOZA',
                'puesto' => 'ASISTENTE DE PLANILLAS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JAIME',
                'apellidos' => 'EDWIN GONZÁLEZ DEL CID',
                'puesto' => 'ASISTENTE DE CONTABILIDAD',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'MYNOR ISAÍ',
                'apellidos' => 'REVOLORIO SALAVERRIA',
                'puesto' => 'ASISTENTE DE CONTABILIDAD',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'NERY ARMANDO',
                'apellidos' => 'LIX VIVAR',
                'puesto' => 'ASISTENTE DE CONTABILIDAD',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JUAN CARLOS',
                'apellidos' => 'LAVARREDA MOLINA',
                'puesto' => 'ASISTENTE DE CONTABILIDAD',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'EDUARDO',
                'apellidos' => 'CHIROY TURUY',
                'puesto' => 'ASISTENTE DE CONTABILIDAD',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'GLENDA MARISOL',
                'apellidos' => 'MIRANDA RODAS',
                'puesto' => 'CONSERJE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'VÍCTOR MANUEL',
                'apellidos' => 'TAY QUISQUINAY',
                'puesto' => 'ENCARGADO DE MANTENIMIENTO',
                'pais_id' => 1,
            ],
            [
                'nombres' => '',
                'apellidos' => 'SAMUEL MEJÍA DE LEÓN',
                'puesto' => 'GERENTE FINANCIERO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'CRISTABEL',
                'apellidos' => 'ARAGÓN HERNÁNDEZ DE JUÁREZ',
                'puesto' => 'JEFE DE CONTABILIDAD',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'AMANDA LIZBETH',
                'apellidos' => 'REVOLORIO GARCÍA DE GÓMEZ',
                'puesto' => 'SUB JEFE DE CONTABILIDAD',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ERICK NOE',
                'apellidos' => 'SOTO ESPINOZA',
                'puesto' => 'CONSERJE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JEREMY ALESSANDRO',
                'apellidos' => 'ORDOÑEZ SOLÍS',
                'puesto' => 'AUXILIAR DE CONTABILIDAD',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'MARCO VINICIO',
                'apellidos' => 'CHÉ PÉREZ',
                'puesto' => 'ASISTENTE DE CONTABILIDAD',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ALLAN WOTZBELY',
                'apellidos' => 'CHAVEZ SOLIZ',
                'puesto' => 'ENCARGADO BODEGA PRODUCTO TERMINADO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'AMILCAR ANTONIO',
                'apellidos' => 'CASTELLANOS SANTOS',
                'puesto' => 'AUXILIAR DE REPARTO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ARNOLDO ELISEO',
                'apellidos' => 'CHOC IXIM',
                'puesto' => 'PREPARADOR Y EMPACADOR',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'CHRISTOPHER KEVIN',
                'apellidos' => 'ALEXANDER GARCIA',
                'puesto' => 'PILOTO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'EDWIN MIGUEL',
                'apellidos' => 'CARDONA SIGUAN',
                'puesto' => 'ASISTENTE DE COSTOS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'EDY ESTUARDO',
                'apellidos' => 'ROMERO GARCIA',
                'puesto' => 'ENCARGADO BODEGA PRODUCTO TERMINADO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ENRIQUE DAVID',
                'apellidos' => 'MARROQUIN ROSALES',
                'puesto' => 'PREPARADOR Y EMPACADOR',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'GERSON LEONARDO',
                'apellidos' => 'RUIZ ALVARADO',
                'puesto' => 'PREPARADOR Y EMPACADOR',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'HECTOR WILFREDO',
                'apellidos' => 'JUAREZ VELASQUEZ',
                'puesto' => 'PREPARADOR Y EMPACADOR',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JAVIER',
                'apellidos' => 'BAMACA VALLE',
                'puesto' => 'JEFE DE BODEGA DE PRODUCTO TERMINADO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JOSE ESTUARDO',
                'apellidos' => 'RODRIGUEZ MARROQUIN',
                'puesto' => 'AUXILIAR DE REPARTO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JOSHUA EMANUEL',
                'apellidos' => 'DÁVILA ALVIZURIS',
                'puesto' => 'PILOTO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'LUIS ENRIQUE',
                'apellidos' => 'ALONZO LÓPEZ',
                'puesto' => 'PREPARADOR Y EMPACADOR',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'LUIS FELIPE',
                'apellidos' => 'AGUILAR GARCÍA',
                'puesto' => 'PREPARADOR Y EMPACADOR',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'PABLO ENRIQUE',
                'apellidos' => 'GIL MEJIA',
                'puesto' => 'JEFE DE TRANSPORTES',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'RANDY GABRIEL',
                'apellidos' => 'BRAN AROCHE',
                'puesto' => 'PREPARADOR Y EMPACADOR',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'WALTER',
                'apellidos' => 'ANTONIO VAZQUEZ',
                'puesto' => 'GERENTE GENERAL',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'VÍCTOR MANUEL',
                'apellidos' => 'ÁLVAREZ IBOY',
                'puesto' => 'ESPECIALISTA EN POWER BI',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'DARWIN',
                'apellidos' => 'ALFONSO RIVERA',
                'puesto' => 'ASISTENTE DE INFORMATICA',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'DAVID ANTONIO',
                'apellidos' => 'BOCALETTI COMPARINI',
                'puesto' => 'ASISTENTE DE INFORMATICA',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'GERMAN GONZALO',
                'apellidos' => 'ECHEVERRÍA PÉREZ',
                'puesto' => 'ASISTENTE DE INFORMATICA',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'AMANDO',
                'apellidos' => 'GUERRA',
                'puesto' => 'GERENTE DE INFORMATICA',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'BRYAN GILBERTO',
                'apellidos' => 'CHALIN GARCIA',
                'puesto' => 'AUXILIAR DE INFORMÁTICA',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'BRITNEY YULIZZA',
                'apellidos' => 'ALFARO ESCOBAR',
                'puesto' => 'ANALISTA I&D',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'DIANA MAGALETH',
                'apellidos' => 'COLINDRES ARGUETA',
                'puesto' => 'AUXILIAR DE INVESTIGACIÓN Y DESARROLLO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JOSE MANUEL',
                'apellidos' => 'TOJ SICAL',
                'puesto' => 'AUXILIAR TÉCNICO DE INVESTIGACION Y DESARROLLO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JOSELINE MARIA',
                'apellidos' => 'ALVAREZ BARILLAS',
                'puesto' => 'ANALISTA DE I&D',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'LEONOR INOCENTE MENDOZA',
                'apellidos' => 'SANCHEZ DE',
                'puesto' => 'JEFE DE ANÁLISIS Y DOCUMENTACIÓN',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'MARIA',
                'apellidos' => 'ISABEL DE LEON SALVATIERRA',
                'puesto' => 'ANALISTA DE I&D',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'MARIA JOSE',
                'apellidos' => 'TOBIAS VASQUEZ',
                'puesto' => 'FORMULADOR DE INVESTIGACION Y DESARROLLO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ORBIN ARIEL',
                'apellidos' => 'LIMA MARROQUÍN',
                'puesto' => 'ESPECIALISTA EN DOCUMENTACIÓN DE I+D',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'PAOLO DAVID ESTEBAN',
                'apellidos' => 'MIJANGOS LOBOS',
                'puesto' => 'ANALISTA DE I&D',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'PAULA DANIELA',
                'apellidos' => 'MENDOZA AZURDIA',
                'puesto' => 'FORMULADOR DE INVESTIGACION Y DESARROLLO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'REYNA LISBETH',
                'apellidos' => 'AREVALO SOTO',
                'puesto' => 'AUXILIAR DE INVESTIGACIÓN Y DESARROLLO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ROLANDO',
                'apellidos' => 'SANTIZO CALDERÓN',
                'puesto' => 'GERENTE DE INVESTIGACIÓN Y DESARROLLO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'VALERIA ESTEFANIA',
                'apellidos' => 'ZAMBONI MORALES',
                'puesto' => 'FORMULADOR DE INVESTIGACION Y DESARROLLO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'WALTER RENATO',
                'apellidos' => 'STEIGER AREVALO',
                'puesto' => 'JEFE DE  DESARROLLO FARMACÉUTICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'WILLIAM DAVID',
                'apellidos' => 'HERNÁNDEZ ESPAÑA',
                'puesto' => 'AUXILIAR TÉCNICO DE I&D',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'WILLIAM RENÉ',
                'apellidos' => 'GARCÍA CORADO',
                'puesto' => 'ANALISTA DE I&D',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'HUGO',
                'apellidos' => 'GARCÍA',
                'puesto' => 'AUDITOR GENERAL',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'SONIA LISSETH',
                'apellidos' => 'AZURDIA ESCOBAR',
                'puesto' => 'ASISTENTE DE JUNTA DIRECTIVA',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'OLIVER DAVID',
                'apellidos' => 'GOMEZ MEJIA',
                'puesto' => 'AUXILIAR DE BODEGA',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ALEJANDRO MANUEL',
                'apellidos' => 'PÉREZ PÉREZ',
                'puesto' => 'AUXILIAR DE MANTENIMIENTO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ANA CANDELARIA',
                'apellidos' => 'CARRERA TRUJILLO',
                'puesto' => 'AUXILIAR DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ANA MARIELA',
                'apellidos' => 'MENDOZA SACAYON',
                'puesto' => 'AUXILIAR DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ANABELLA',
                'apellidos' => 'OLIVA PAZ',
                'puesto' => 'AUXILIAR DE MANTENIMIENTO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ANDREA',
                'apellidos' => 'LOPEZ VASQUEZ',
                'puesto' => 'AUXILIAR DE SOLUCIONES ESTERILES',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ANDREA MARILU',
                'apellidos' => 'ALVAREZ LOPEZ',
                'puesto' => 'AUXILIAR DE SOLUCIONES ESTERILES',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ANGEL EMANUEL',
                'apellidos' => 'FAJARDO CHÁVEZ',
                'puesto' => 'OPERADOR DE IMPRESIÓN FLEXOGRÁFICA',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ÁNGEL GONZALO',
                'apellidos' => 'SAPÓN ORDOÑEZ',
                'puesto' => 'AUXILIAR DE BODEGA',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ANGELA',
                'apellidos' => 'MARÍA LEMUS',
                'puesto' => 'AUXILIAR DE MANTENIMIENTO PRODUCCIÓN',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ARACELY CRISTOBALINA',
                'apellidos' => 'CHIC LOPEZ',
                'puesto' => 'AUXILIAR DE SOLUCIONES ESTERILES',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ARLEN MAYTE',
                'apellidos' => 'FLORES MORALES',
                'puesto' => 'AUXILIAR DE MANUFACTURA DE SOLUCIONES ESTÉRILES',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'BLANCA ISABEL',
                'apellidos' => 'PÉREZ TICAS',
                'puesto' => 'OPERADOR EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'BRISEIDA IDANIA',
                'apellidos' => 'BERNABE MARTÍNEZ',
                'puesto' => 'AUXILIAR DE SOLUCIONES ESTERILES',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'BRYAN ARMANDO',
                'apellidos' => 'TORRES TORRES',
                'puesto' => 'AUXILIAR DE BODEGA',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'BYRON RANDOLFO',
                'apellidos' => 'GALICIA GONZÁLEZ',
                'puesto' => 'ENCARGADO DE GRANULADO Y MEZCLADO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'CARLOS ARMANDO',
                'apellidos' => 'BARILLAS NUÑEZ',
                'puesto' => 'ENCARGADO DE LINEAS DE EMPAQUE Y LLENADO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'CARLOS BENJAMIN',
                'apellidos' => 'PASCUAL LOPEZ',
                'puesto' => 'ENCARGADO DE GRANULADO Y MEZCLADO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'CARLOS GIOVANNI',
                'apellidos' => 'ALFARO SAZO',
                'puesto' => 'MECÁNICO/SOLDADOR',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'CARLOS MAURICIO',
                'apellidos' => 'GARCIA MARROQUIN',
                'puesto' => 'ENCARGADO MANUFACTURA DE SOLUCIONES ESTERILES',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'CECILIA NICTE',
                'apellidos' => 'SUCUP MORAN',
                'puesto' => 'SUPER.DE LIQUIDOS Y SOLUCIONES ESTERILES',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'CINTHYA ALEJANDRA',
                'apellidos' => 'MEJIA RAYMUNDO',
                'puesto' => 'AUXILIAR DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'CLAUDIA CELESTE',
                'apellidos' => 'SÁNCHEZ SIL',
                'puesto' => 'DIGITADORA DE BODEGA DE INSUMOS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'CLAUDIA ZUCELY',
                'apellidos' => 'GODOY REYES',
                'puesto' => 'AUXILIAR DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'CRISTIAN ANDRES',
                'apellidos' => 'PEREZ SUCHITE',
                'puesto' => 'SUPERVISOR AREA DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'CRISTIAN GUILLERMO',
                'apellidos' => 'MUÑIZ ORTIZ',
                'puesto' => 'ENCARGADO DE GRANULADO Y MEZCLADO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'CRISTINA',
                'apellidos' => 'PETRONA DE LEON RAYMUNDO',
                'puesto' => 'OPERADOR EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'DANIEL HUMBERTO',
                'apellidos' => 'MELENDREZ RAMÍREZ',
                'puesto' => 'ENCARGADO DE RECUBRIMIENTO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'DAVID TOMÁS',
                'apellidos' => 'BÁMACA VELÁSQUEZ',
                'puesto' => 'ASISTENTE DE PLANIFICACIÓN DE PRODUCCIÓN',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'DEBORA MICHELLE',
                'apellidos' => 'GONZALEZ AMBROSIO',
                'puesto' => 'OPERADOR EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'DULBIN ESDUARDO',
                'apellidos' => 'RAMIREZ VELASQUEZ',
                'puesto' => 'JEFE  DE BODEGA INSUMOS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'EDDIN LEONEL',
                'apellidos' => 'TUBIN ORDOÑEZ',
                'puesto' => 'ENCARGADO DE BODEGA DE SEMIELABORADO Y PT',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'EDGAR CRISTOBAL',
                'apellidos' => 'RAMOS ROSALES',
                'puesto' => 'AUXILIAR DE MANTENIMIENTO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'EDGAR EMMANUEL',
                'apellidos' => 'AGUILAR ARRIVILLAGA',
                'puesto' => 'ELECTRICISTA',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ELICENDA ELIZABETH',
                'apellidos' => 'GALINDO IXCHOP',
                'puesto' => 'AUXILIAR DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ELODIA DELGADINA',
                'apellidos' => 'RODAS REYES',
                'puesto' => 'AUXILIAR DE MANTENMIENTO PRODUCCIÓN',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ELSA ELVIRA',
                'apellidos' => 'OROZCO RAMIREZ',
                'puesto' => 'ENCARGADO (A) DE LAVANDERIA',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ERASMO ALBERTO',
                'apellidos' => 'LOPEZ PEREZ',
                'puesto' => 'TÉCNICO DE AGUAS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ERIKA',
                'apellidos' => 'NATALICHA VELÁSQUEZ',
                'puesto' => 'AUXILIAR DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ESTHER OLINDA',
                'apellidos' => 'ISMALEJ ALVARADO',
                'puesto' => 'DIGITADORA DE BODEGA INSUMOS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ESTUARDO EMANUEL',
                'apellidos' => 'MENDEZ BATRES',
                'puesto' => 'AUXILIAR DE SÓLIDOS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ETELBINA DE JESUS',
                'apellidos' => 'HERNANDEZ BARRERA',
                'puesto' => 'ENCARGADO DE LLENADO DE SOLUCIONES ESTERILES',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'EVER ESTUARDO',
                'apellidos' => 'VÁSQUEZ LÓPEZ',
                'puesto' => 'ELECTRICISTA',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'FELIPE ANTONIO',
                'apellidos' => 'GONZALEZ SIAN',
                'puesto' => 'ENCARGADO DE GRANULADO Y MEZCLADO',
                'pais_id' => 1,
            ],
            [
                'nombres' => '',
                'apellidos' => 'FLORIDALMA RAMIREZ DE PAZ',
                'puesto' => 'ENCARGADO DE LAVADO Y ESTERILIZADO DE ENVASE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'FRANCISCO EMANUEL',
                'apellidos' => 'HERNÁNDEZ TUNCHEZ',
                'puesto' => 'AUXILIAR DE BODEGA',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'GABRIELA MAGALI',
                'apellidos' => 'TEPET PEREZ',
                'puesto' => 'ENCARGADO (A) DE LAVANDERIA',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'GLENDA AZUCENA',
                'apellidos' => 'ARANA LUCERO',
                'puesto' => 'AUXILIAR DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'HECTOR DAVID',
                'apellidos' => 'GONZALEZ NOJ',
                'puesto' => 'ENCARGADO DE PESADOS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'LITZY ALEJANDRA',
                'apellidos' => 'RAMOS ESTEBAN',
                'puesto' => 'AUXILIAR DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'SOFIA ELIZABETH',
                'apellidos' => 'MARTÍNEZ HERNÁNDEZ',
                'puesto' => 'AUXILIAR DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'HECTOR FERNANDO',
                'apellidos' => 'LUCERO ARGUETA',
                'puesto' => 'ENCARGADO DE TABLETEADO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'HENDRIX DHABI',
                'apellidos' => 'OBANDO COS',
                'puesto' => 'ASISTENTE DE DISEÑO GRÁFICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'HENRY AARÓN',
                'apellidos' => 'DONIZ GARCÍA',
                'puesto' => 'TÉCNICO EN DIBUJO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'HEYDI ARACELY',
                'apellidos' => 'LÓPEZ CALDERÓN',
                'puesto' => 'OPERADOR DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'HUGO RENE',
                'apellidos' => 'CUYAN ALONZO',
                'puesto' => 'ENCARGADO DE TABLETEADO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'IDANIA MARICARMEN',
                'apellidos' => 'CHAPETON TUBAC',
                'puesto' => 'AUXILIAR DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'INGRID CAROLINA',
                'apellidos' => 'BETANCOURTH JUAREZ',
                'puesto' => 'AUXILIAR DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'INGRID ELIZABETH',
                'apellidos' => 'LÓPEZ ALARCÓN',
                'puesto' => 'OPERADOR DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'IRMA LETICIA',
                'apellidos' => 'PINZON VASQUEZ',
                'puesto' => 'AUXILIAR DE MANTENIMIENTO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JACKELINE LEHONOR',
                'apellidos' => 'AJANEL HERNÁNDEZ',
                'puesto' => 'OPERADOR EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JAIRON NAHUM',
                'apellidos' => 'AJXUP MORAN',
                'puesto' => 'AUXILIAR DE MANTENIMIENTO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JAQUELINE ARCELI',
                'apellidos' => 'QUIÑONEZ GARCÍA',
                'puesto' => 'OPERADOR DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JENIFER FABIOLA',
                'apellidos' => 'TRUJILO SORIANO',
                'puesto' => 'OPERADORA DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JENNIFER GUADALUPE',
                'apellidos' => 'LÓPEZ CJCHUM',
                'puesto' => 'ENCARGADA DE OPERACIONES DE PLANIFICACIÓN',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JENNIFER MISHEL',
                'apellidos' => 'LOCON BLANCO',
                'puesto' => 'OPERADOR DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JENNIFER YESSENIA',
                'apellidos' => 'LÓPEZ MARTÍNEZ',
                'puesto' => 'AUXILIAR DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JESSENIA CLARIVEL',
                'apellidos' => 'RODRIGUEZ SOSA',
                'puesto' => 'OPERADOR DE LLENADO DE SOLUCIONES ESTÉRILES',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JOEL ANTONIO',
                'apellidos' => 'CABRERA BORGE',
                'puesto' => 'AUXILIAR DE MANUFACTURA DE LIQUIDOS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JONATAN',
                'apellidos' => 'DAVID DE LEON BRAVO',
                'puesto' => 'PLANIFICADOR DE PRODUCCION JUNIOR',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JORGE ALBERTO',
                'apellidos' => 'REYES ESTUPINIAN',
                'puesto' => 'AUXILIAR DE MANTENIMIENTO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JORGE ALFREDO',
                'apellidos' => 'SANDOVAL GARCÍA',
                'puesto' => 'PLANIFICADOR DE LA DEMANDA',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JOSE ALEJANDRO',
                'apellidos' => 'LEONARDO CEBALLOS',
                'puesto' => 'JEFE DE PRODUCCION',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JOSE',
                'apellidos' => 'DANIEL JUAREZ',
                'puesto' => 'SUPERVISOR DE MANTENIMIENTO.',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'JOSUÉ ALEJADRO',
                'apellidos' => 'CRISTALES RAMOS',
                'puesto' => 'AUXILIAR DE BODEGA',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'KARLA ALEJANDRA',
                'apellidos' => 'BATZ BRAVO',
                'puesto' => 'AUXILIAR DE MANTENIMIENTO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'KARLA',
                'apellidos' => 'VANESSA SONTAY',
                'puesto' => 'AUXILIAR DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'KATERIN',
                'apellidos' => 'MISHEL DÁVILA',
                'puesto' => 'AUXILIAR DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'KATHERIN GUADALUPE',
                'apellidos' => 'GARCÍA GÓMEZ',
                'puesto' => 'AUXILIAR DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'KELLY',
                'apellidos' => 'YULIZA QUEZADA DE PAZ',
                'puesto' => 'AUXILIAR DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'KENNETH REYNALDO',
                'apellidos' => 'CARDONA GRAMAJO',
                'puesto' => 'AUXILIAR DE BODEGA',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'LESLI YECENIA',
                'apellidos' => 'LÓPEZ BARAHONA',
                'puesto' => 'OPERADOR DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'LESLIN MARICELA',
                'apellidos' => 'MARTÍN LÓPEZ',
                'puesto' => 'AUXILIAR DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'LETICIA IRACEMA',
                'apellidos' => 'ESTRADA AVALOS',
                'puesto' => 'ENCARGADO DE IMPRESIONES DE VIALES Y AMPOLLAS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'LILIAN AMARILIS',
                'apellidos' => 'GALICIA GARCÍA',
                'puesto' => 'AUXILIAR DE SOLUCIONES ESTERILES',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'LUCIA',
                'apellidos' => 'PIRIR GONZALEZ',
                'puesto' => 'AUXILIAR DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'LUCINDA',
                'apellidos' => 'ANDRÉS LÓPEZ DE GARCÍA',
                'puesto' => 'AUXILIAR DE SOLUCIONES ESTÉRILES',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'LUIS FERNANDO',
                'apellidos' => 'AMAYA BORRAYOS',
                'puesto' => 'ENC. DE OPERACIONES DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'LUIS FERNANDO',
                'apellidos' => 'BONILLA RAMOS',
                'puesto' => 'ENCARGADO DE BODEGA DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'LUIS FERNANDO',
                'apellidos' => 'SAGASTUME CONTRERAS',
                'puesto' => 'AUXILIAR DE MANTENIMIENTO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'LUIS',
                'apellidos' => 'MISAEL LOPEZ',
                'puesto' => 'ASIST.MANTENIMIENTO EQUIPO E INSTALACION',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'LUZ ENEIDA',
                'apellidos' => 'PEREZ RODRIGUEZ',
                'puesto' => 'AUXILIAR DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'MADELIN ESPERANZA',
                'apellidos' => 'HERNANDEZ MARROQUÍN',
                'puesto' => 'AUXILIAR DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'MAGNOLIA ELIZABETH',
                'apellidos' => 'VELASQUEZ SIAN',
                'puesto' => 'AUXILIAR DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'MARCO VICTORIANO',
                'apellidos' => 'GUZMÁN AKAZAKI',
                'puesto' => 'ENCARGADO DE PESADOS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'MARÍA ANGÉLICA',
                'apellidos' => 'BARRIOS GARCÍA',
                'puesto' => 'AUXILIAR DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'MARÍA ANGÉLICA',
                'apellidos' => 'SOSA BRAVO',
                'puesto' => 'AUXILIAR DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'MARIA ANTONIA',
                'apellidos' => 'JUAREZ SALAZAR',
                'puesto' => 'ENCARGADO (A) DE LAVANDERIA',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'MARIA CONSUELO',
                'apellidos' => 'MINERA GONZALEZ',
                'puesto' => 'ASISTENTE DE GERENCIA DE PRODUCCIÓN',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'MARIA DEL CARMEN',
                'apellidos' => 'LÓPEZ AVILA',
                'puesto' => 'AUXILIAR DE SOLUCIONES ESTÉRILES',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'MARIELA',
                'apellidos' => 'BARRIOS ARRIOLA',
                'puesto' => 'DISEÑADOR GRAFICO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'MARISELA',
                'apellidos' => 'CHUMIL MORALES',
                'puesto' => 'AUXILIAR DE SOLUCIONES ESTERILES',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'MAYRA JANETH',
                'apellidos' => 'COCÓN AMBROSIO',
                'puesto' => 'AUXILIAR DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'MAYRA LISBETH',
                'apellidos' => 'AMBROSIO QUEZADA',
                'puesto' => 'AUXILIAR DE SOLUCIONES ESTÉRILES',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'MELANY',
                'apellidos' => 'ABIGAIL DIEGUEZ DE LEÓN',
                'puesto' => 'AUXILIAR DE SOLUCIONES ESTERILES',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'MIGUEL ANGEL',
                'apellidos' => 'SANCHEZ LORENZO',
                'puesto' => 'MECANICO SOLDADOR',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'MIGUEL',
                'apellidos' => 'ANTONIO PINEDA DEL CID',
                'puesto' => 'ENCARGADO DE MANUFCTURA DE LÍQUIDOS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'MILDRED JANETH',
                'apellidos' => 'SUY GARCIA',
                'puesto' => 'AUXILIAR DE SOLUCIONES ESTERILES',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'MILDRED LISSETTE',
                'apellidos' => 'GOMEZ GARCIA',
                'puesto' => 'ENCARGADA DE LÍNEAS Y LLENADO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'MIRNA ROXANA',
                'apellidos' => 'GARCÍA SABAN',
                'puesto' => 'AUXILIAR DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'MYNOR EDUARDO',
                'apellidos' => 'ALVAREZ MARTINEZ',
                'puesto' => 'ENCARGADO BODEGA DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'NADESHNA CONSUELO',
                'apellidos' => 'ALARCON ARCHILA',
                'puesto' => 'JEFE DE PLANIFICACION Y COMPRAS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'NAIROBI DANIELA S.',
                'apellidos' => 'SÁNCHEZ MORATAYA',
                'puesto' => 'AUXILIAR DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'NANCY NOEMI',
                'apellidos' => 'REYNOSO CIFUENTES',
                'puesto' => 'AUXILIAR DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'NAYDELIN LAISHA',
                'apellidos' => 'MEJÍA OROZCO',
                'puesto' => 'ENCARGADA DE RECUBRIMIENTO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'NEHEMIAS EVERILDO',
                'apellidos' => 'MENDEZ SANTIZO',
                'puesto' => 'ELECTRICISTA',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'NELSON DANILO',
                'apellidos' => 'MORALES GARCÍA',
                'puesto' => 'ENCARGADO DE TABLETEADO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'NEREIDA VIOLETA',
                'apellidos' => 'CAAL COC',
                'puesto' => 'AUXILIAR DE SOLUCIONES ESTÉRILES',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'NICOLAS ALEJANDRO',
                'apellidos' => 'ZET AJSOC',
                'puesto' => 'ENCARGADO DE RECUBRIMIENTO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'OLGA ANAÍ',
                'apellidos' => 'LÓPEZ CHITIC',
                'puesto' => 'AUXILIAR DE SOLUCIONES ESTERILES',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ORFA ZULENI',
                'apellidos' => 'JIMÉNEZ CALMO',
                'puesto' => 'AUXILIAR DE BODEGA DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ORLANDO LEONEL',
                'apellidos' => 'ARENAS MENDEZ',
                'puesto' => 'ENCARGADO BODEGA DE REPUESTOS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'OSCAR ALBERTO',
                'apellidos' => 'GARCIA HIGUEROS',
                'puesto' => 'AUXILIAR AREA SOLIDOS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'OSCAR LEONEL',
                'apellidos' => 'FAJARDO BARRIOS',
                'puesto' => 'ASISTENTE DE COMPRAS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'PABLO EMILIO',
                'apellidos' => 'DÍAZ IRLA',
                'puesto' => 'ENCARGADO DE GRANULADO Y MEZCLADO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'RAFAEL EDUARDO',
                'apellidos' => 'PALALA ORTÍZ',
                'puesto' => 'SUPERVISOR DE SÓLIDOS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'RICARDO',
                'apellidos' => 'ANDRES DEL CID PELAEZ',
                'puesto' => 'MENSAJERO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ROLANDO ULISSES',
                'apellidos' => 'ESCOBAR ACEITUNO',
                'puesto' => 'GERENTE DE PRODUCCION',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'RONALD',
                'apellidos' => 'JOSE DEL CID BARRIENTOS',
                'puesto' => 'JEFE DE MANTENIMIENTO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'RONI GABRIEL',
                'apellidos' => 'MUÑOZ RODRIGUEZ',
                'puesto' => 'AUXILIAR AREA SOLIDOS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'ROSA ANGELICA',
                'apellidos' => 'LOPEZ RENDEROS',
                'puesto' => 'OPERADOR EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'SANDRA NOHEMY',
                'apellidos' => 'MEDINA HERNÁNDEZ',
                'puesto' => 'AUXILIAR DE SOLUCIONES ESTÉRILES',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'SANDRA PATRICIA',
                'apellidos' => 'GONZÁLEZ VÁSQUEZ',
                'puesto' => 'ENCARGADA DE LÍNEAS Y LLENADOS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'SANDRA PATRICIA',
                'apellidos' => 'GUZMÁN BARRIOS',
                'puesto' => 'ASISTENTE ADMINISTRATIVO DE MANTENIMIENTO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'SARA GABRIELA',
                'apellidos' => 'SOLIS BAMACA',
                'puesto' => 'OPERADOR DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'SEBASTIAN RAFAEL',
                'apellidos' => 'HERNANDEZ VASQUEZ',
                'puesto' => 'INGENIERO DE PROCESOS JR',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'SELVIN',
                'apellidos' => 'RUIZ RAMOS',
                'puesto' => 'ENCARGADO DE REUCRIMIENTO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'SILVIA FRANCISCA',
                'apellidos' => 'SIMAJ LAYNEZ',
                'puesto' => 'AUXILIAR DE SOLUCIONES ESTERILES',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'SONIA',
                'apellidos' => 'VIVIANA DE LEON LOPEZ',
                'puesto' => 'AUXILIAR DE MANTENIMIENTO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'SULY ANABELA',
                'apellidos' => 'LARA MONGE',
                'puesto' => 'ENCARGADA DE RECUBRIMIENTO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'SUSANA YAMILETH',
                'apellidos' => 'PU RETANA',
                'puesto' => 'AUXILIAR DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'VERÓNICA MARGARITA',
                'apellidos' => 'ELIAS MORO',
                'puesto' => 'AUXILIAR DE SOLUCIONES ESTÉRILES',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'VICENTE ALEJANDRO',
                'apellidos' => 'GARCIA HERNANDEZ',
                'puesto' => 'ASISTENTE DE COMPRAS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'VÍCTOR ESTUARDO',
                'apellidos' => 'ANDRADE ROSALES',
                'puesto' => 'JEFE DE PLANIFICACION DE PRODUCCION',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'VILMA ODILIA',
                'apellidos' => 'AFRE PONSOY',
                'puesto' => 'AUXILIAR DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'WALFRE IRENIO',
                'apellidos' => 'BATRES VÁSQUEZ',
                'puesto' => 'AUXILIAR DE BODEGA',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'WALTER SAÚL',
                'apellidos' => 'BRAVO LÓPEZ',
                'puesto' => 'AUXILIAR DE BODEGA',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'WAUNER SALVADOR',
                'apellidos' => 'HERNÁNDEZ MORENTE',
                'puesto' => 'AUXILIAR DE BODEGA',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'WENDY GABRIELA',
                'apellidos' => 'CHAJÓN VELÁSQUEZ',
                'puesto' => 'AUXILIAR DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'WENDY LISETH',
                'apellidos' => 'LOPEZ ESPINOZA',
                'puesto' => 'OPERADOR EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'WENDY MAGALI',
                'apellidos' => 'ONOFRE TREJO',
                'puesto' => 'AUXILIAR DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'WENDY NOHEMY',
                'apellidos' => 'LEMUS HERNÁNDEZ',
                'puesto' => 'AUXILIAR DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'WENDY ROXANA',
                'apellidos' => 'GARCÍA GARACÍA',
                'puesto' => 'AUXILIAR DE SOLUCIONES ESTÉRILES',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'WILTON',
                'apellidos' => 'AUGUSTO TORRES',
                'puesto' => 'ENCARGADO DE  OPERACIONES',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'YELIN EDITH',
                'apellidos' => 'PÉREZ AJANEL',
                'puesto' => 'AUXILIAR DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'YENDY ROXANA',
                'apellidos' => 'MATEO PÉREZ',
                'puesto' => 'ENCARGADA DE OPERACIONES',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'YENIFER AZUCENA',
                'apellidos' => 'GARCIA SICAY',
                'puesto' => 'AUXILIAR DE SOLUCIONES ESTERILES',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'YESSENIA ELICEC',
                'apellidos' => 'RODRIGUEZ BARRIENTOS',
                'puesto' => 'AUXILIAR DE MANTENIMIENTO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'YOSIRLIN ROSEMERY',
                'apellidos' => 'PÉREZ GARCÍA',
                'puesto' => 'AUXILIAR DE EMPAQUE',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'VERÓNICA',
                'apellidos' => 'ILLESCAS',
                'puesto' => 'RECEPCIONISTA',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'DIANA IRMINGAERTH',
                'apellidos' => 'VIELMAN VILLEGAS',
                'puesto' => 'GERENTE DE RECURSOS HUMANOS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'MÁRIEL IVANOVA',
                'apellidos' => 'CETINO HERRERA',
                'puesto' => 'ESPECIALISTA EN SELECCIÓN Y CULTURA',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'DÁMARIS JANET',
                'apellidos' => 'ROSALES MELÉNDEZ',
                'puesto' => 'ESPECIALISTA EN GESTIÓN DEL DESEMPEÑO Y DO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'CAROL ILEANA',
                'apellidos' => 'CARRILLO ENRIQUEZ',
                'puesto' => 'JEFE RECURSOS HUMANOS LABORATORIO',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'DANIEL ALEXANDER',
                'apellidos' => 'MARROQUÍN GARCÍA',
                'puesto' => 'MÉDICO OCUPACIONAL',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'MARIA DEL ROSARIO',
                'apellidos' => 'MONTERROSO ORTIZ',
                'puesto' => 'ASISTENTE DE RECURSOS HUMANOS',
                'pais_id' => 1,
            ],
            [
                'nombres' => 'YANELY MAGDONY',
                'apellidos' => 'RODRÍGUEZ GIRÓN',
                'puesto' => 'JEFE SALUD Y SEGURIDAD OCUPACIONAL',
                'pais_id' => 1,
            ],

            //?  HONDURAS  ?//
            [
                'nombres'   => 'NAIDELIN ALEJANDRA',
                'apellidos' => 'QUIROZ PADILLA',
                'puesto'    => 'PROMOTOR SAN PEDRO SULA',
                'pais_id'   => 2,
            ],
            [
                'nombres'   => 'MARCIA ELIZETH',
                'apellidos' => 'BORJAS RIVAS',
                'puesto'    => 'GERENTE DE PAÍS HONDURAS',
                'pais_id'   => 2,
            ],
            [
                'nombres'   => 'KAREN JULISSA',
                'apellidos' => 'BRIZUELA GARCÍA',
                'puesto'    => 'COORDINADOR DE VISITA MÉDICA ZONA NORTE',
                'pais_id'   => 2,
            ],
            [
                'nombres'   => 'DANIEL EDUARDO',
                'apellidos' => 'ROSALES CANALES',
                'puesto'    => 'VISITADOR MÉDICO SAN PEDRO SULA',
                'pais_id'   => 2,
            ],
            [
                'nombres'   => 'KELLYN NOHEMY',
                'apellidos' => 'MADRID GONZÁLEZ',
                'puesto'    => 'VISITADOR MÉDICO SAN PEDRO SULA',
                'pais_id'   => 2,
            ],
            [
                'nombres'   => 'PEDRO ENRIQUE',
                'apellidos' => 'CHAVARRÍA ZAVALA',
                'puesto'    => 'VISITADOR MÉDICO SAN PEDRO SULA',
                'pais_id'   => 2,
            ],
            [
                'nombres'   => 'MANUEL ARMANDO',
                'apellidos' => 'NÚÑEZ FUNES',
                'puesto'    => 'VISITADOR MÉDICO TEGUCIGALPA',
                'pais_id'   => 2,
            ],
            [
                'nombres'   => 'BEATRIZ ALEJANDRA',
                'apellidos' => 'CARRASCO ÁVILA',
                'puesto'    => 'VISITADOR MÉDICO TEGUCIGALPA',
                'pais_id'   => 2,
            ],
            [
                'nombres'   => 'JOSUÉ ANDRÉS',
                'apellidos' => 'PINEDA SANTOS',
                'puesto'    => 'VISITADOR MÉDICO TEGUCIGALPA',
                'pais_id'   => 2,
            ],
            [
                'nombres'   => 'MYLDRED YANELY',
                'apellidos' => 'AGUIRRE HERNÁNDEZ',
                'puesto'    => 'PROMOTOR TEGUCIGALPA',
                'pais_id'   => 2,
            ],
            [
                'nombres'   => 'NELLY ESTHER',
                'apellidos' => 'VARELA VALERIANO',
                'puesto'    => 'PROMOTOR TEGUCIGALPA',
                'pais_id'   => 2,
            ],
            [
                'nombres'   => 'MARTHA KARINA',
                'apellidos' => 'FLORES INESTROZA',
                'puesto'    => 'PROMOTOR SAN PEDRO SULA',
                'pais_id'   => 2,
            ],
            [
                'nombres'   => 'DAISY GABRIELA',
                'apellidos' => 'PEREZ SANCHEZ',
                'puesto'    => 'VISITADOR MEDICO TEGUCIGALPA',
                'pais_id'   => 2,
            ],
            [
                'nombres'   => 'DERICK ALBERTO',
                'apellidos' => 'BLACKBURN ALVARADO',
                'puesto'    => 'VISITADOR MÉDICO SAN PEDRO SULA',
                'pais_id'   => 2,
            ],
            [
                'nombres'   => 'NOLAN EMIL',
                'apellidos' => 'RIVAS O´HARA',
                'puesto'    => 'VISITADOR MÉDICO CHOLUTECA',
                'pais_id'   => 2,
            ],
            [
                'nombres'   => 'RENÉ ALEJANDRO',
                'apellidos' => 'LAZO MARTÍNEZ',
                'puesto'    => 'VISITADOR MÉDICO LA CEIBA',
                'pais_id'   => 2,
            ],
            [
                'nombres'   => 'RUTH ELIZABETH',
                'apellidos' => 'COLINDRES MEDINA',
                'puesto'    => 'ASISTENTE ADMINISTRATIVO TEGUCIGALPA',
                'pais_id'   => 2,
            ],
        ];

        foreach($lab_users as $index => $lab_user) {
            $user = User::create([
                'nombres'                => $lab_user['nombres'],
                'apellidos'              => $lab_user['apellidos'],
                'puesto'                 => $lab_user['puesto'] ?? null,
                'pais_id'                => $lab_user['pais_id'],
                'user_type_id'           => 3,
                'email'                  => 'user'.($index + 1).'@donovan.com',
                'password'               =>  Hash::make(env('DEFAULT_PASS')),
            ]);

            $user->assignRole('employee');
        }

        
    }
}
